# Generates publication digests from embedded catalog.
$ErrorActionPreference = "Stop"
$root = Split-Path (Split-Path $PSScriptRoot -Parent) -ErrorAction SilentlyContinue
# script lives in repo/scripts
$root = Split-Path $PSScriptRoot -Parent
if (-not $root) { throw "Could not resolve repository root from scripts/" }
$pubDir = Join-Path $root "publications"
New-Item -ItemType Directory -Force -Path $pubDir | Out-Null

$items = @(
  @{ slug="new-compiler-stack-survey"; title="The New Compiler Stack: A Survey on the Synergy of LLMs and Compilers"; year="2026"; kind="paper"; group="Surveys & vision"; url="https://arxiv.org/abs/2601.02045"; contrib=@("Multi-dimensional taxonomy: Selector / Translator / Generator","Maps LLM methodology, abstraction level, and task type","Argues hybrid systems are the most promising path"); summary="Systematic survey of LLM-enabled compilation. Frames how LLMs integrate into compilers and highlights correctness/scalability as central challenges."; takeaways=@("Use Selector/Translator/Generator when classifying new work","Hybrid validation beats free-form LLM rewrite","Good roadmap paper for onboarding") },
  @{ slug="compiler-next"; title="Compiler.next: A Search-Based Compiler to Power the AI-Native Future of Software Engineering"; year="2025"; kind="paper"; group="Surveys & vision"; url="https://arxiv.org/html/2510.24799v2"; contrib=@("Vision of SE 3.0 intent/FMware compilation","Treats prompts, agents, and free parameters as compile targets","Lists 10 community calls to action"); summary="Position paper arguing future compilers must search over multi-objective spaces that include LLM prompts and agent configurations, with quality gates and reproducible traces."; takeaways=@("Broadens 'compilation' beyond binaries","Useful checklist for FMware tooling gaps","Still mostly agenda-setting vs shipping system") },
  @{ slug="mlir-formal-theories"; title="Reading AI Model Compilation in MLIR Through the Lens of Formal Theories"; year="2026"; kind="paper"; group="Surveys & vision"; url="https://doi.org/10.48550/arxiv.2606.25244"; contrib=@("Connects MLIR lowering stacks to formal notions","Discusses agent-written compiler-grade code","Surveys vendor MLIR AI compilers"); summary="Explains AI model compilation as layered IR commitments and relates them to term rewriting and related formal ideas; notes falling cost of writing passes via agents."; takeaways=@("Good conceptual bridge for PL + MLIR readers","Positions agents as compiler-engineering accelerators","Not an empirical agent benchmark") },
  @{ slug="tvm-osdi18"; title="TVM: An Automated End-to-End Optimizing Compiler for Deep Learning"; year="2018"; kind="paper"; group="Classic DL compilers"; url="https://www.usenix.org/conference/osdi18/presentation/chen"; contrib=@("End-to-end DL compiler stack","Graph + tensor lowering with autotuning hooks","Open ecosystem that seeded AutoTVM/Ansor"); summary="Foundational system paper for compiling deep learning workloads across hardware with automated optimization."; takeaways=@("Baseline for all later neural/LLM compiler work","Separates graph opts from tensor schedules","Still the conceptual ancestor of many stacks") },
  @{ slug="ansor-osdi20"; title="Ansor: Generating High-Performance Tensor Programs for Deep Learning"; year="2020"; kind="paper"; group="Classic DL compilers"; url="https://www.usenix.org/conference/osdi20/presentation/zheng"; contrib=@("Template-free evolutionary auto-scheduling","Automatic search space construction","Strong empirical wins vs manual templates"); summary="Shows that evolutionary search over automatically derived tensor program spaces can outperform template-based AutoTVM-style tuning."; takeaways=@("Predecessor to MetaSchedule-era search","LLM+MCTS papers often compare against this lineage","Search cost remains a key pain point agents try to cut") },
  @{ slug="tvm-ansor-blog"; title="TVM blog: Introducing Auto-scheduler (Ansor)"; year="2021"; kind="company"; group="Classic DL compilers"; url="https://tvm.apache.org/2021/03/03/intro-auto-scheduler"; contrib=@("Accessible explainer of Ansor in TVM","Integration and tutorial pointers"); summary="Project blog introducing Ansor auto-scheduler to practitioners."; takeaways=@("Good onboarding before reading the OSDI paper","Shows industry/community packaging of research") },
  @{ slug="flextensor-asplos20"; title="FlexTensor: An Automatic Schedule Exploration and Optimization Framework"; year="2020"; kind="paper"; group="Classic DL compilers"; url="https://doi.org/10.1145/3373376.3378508"; contrib=@("Heterogeneous schedule exploration","Combines heuristics and ML for schedules"); summary="ASPLOS system for automatic tensor schedule exploration across CPU/GPU/FPGA-class targets."; takeaways=@("Another pillar of pre-LLM autotune","Useful related work for Reasoning Compiler lineage") },
  @{ slug="tensorir-asplos"; title="TensorIR: An Abstraction for Automatic Tensorized Program Optimization"; year="2022"; kind="paper"; group="Classic DL compilers"; url="https://dl.acm.org/doi/10.1145/3575693.3576933"; contrib=@("Tensor computations as first-class IR","Enables tensorized intrinsic scheduling","Underpins modern TVM TIR scheduling"); summary="Compiler abstraction that generalizes loop nests for tensor primitives and automatic optimization."; takeaways=@("IR design enables later search/LLM proposal methods","Read with MetaSchedule docs") },
  @{ slug="mlir-arxiv"; title="MLIR: A Compiler Infrastructure for the End of Moore's Law"; year="2021"; kind="paper"; group="Classic DL compilers"; url="https://arxiv.org/abs/2002.11054"; contrib=@("Multi-level dialect infrastructure","Reusable passes, verifiers, lowering framework","Became substrate for AI compilers"); summary="Introduces MLIR as extensible multi-level IR infrastructure addressing fragmentation across domain compilers."; takeaways=@("Essential background for AI compiler engineers","Dialects = agent-addressable intermediate languages (in theory)") },
  @{ slug="stablehlo-roadmap"; title="OpenXLA StableHLO roadmap"; year="2025"; kind="company"; group="Classic DL compilers"; url="https://openxla.org/stablehlo/roadmap"; contrib=@("Portable HLO between frameworks and compilers","Versioning/compatibility goals","MHLO migration plans"); summary="Official roadmap for StableHLO as the portability layer across TF/JAX/PyTorch producers and XLA/IREE consumers."; takeaways=@("Key interoperability surface for multi-framework agents","Watch composites and hardware-independent opts") },
  @{ slug="mlgo-paper"; title="MLGO: a Machine Learning Guided Compiler Optimizations Framework"; year="2021"; kind="paper"; group="MLGO & RL gyms"; url="https://arxiv.org/abs/2101.04808"; contrib=@("Industrial ML policies inside LLVM","Inlining-for-size case study","Released into LLVM ecosystem"); summary="First full industrial integration story for learned policies replacing heuristics in a complex LLVM pass."; takeaways=@("Production path for learned advisors","Contrast with Magellan's C++ heuristic synthesis later") },
  @{ slug="mlgo-google-blog"; title="Google Research blog: MLGO"; year="2022"; kind="company"; group="MLGO & RL gyms"; url="https://research.google/blog/mlgo-a-machine-learning-framework-for-compiler-optimization/"; contrib=@("Public narrative for MLGO","Inlining size + regalloc performance results"); summary="Google blog summarizing MLGO motivation, RL training, and production deployments."; takeaways=@("Accessible entry before the paper","Shows QPS/size metrics used in industry") },
  @{ slug="mlgo-infoq"; title="InfoQ: MLGO Framework Brings Machine Learning in Compiler Optimizations"; year="2022"; kind="company"; group="MLGO & RL gyms"; url="https://www.infoq.com/news/2022/07/MLGO-framework-machine-learning/"; contrib=@("Trade-press summary of MLGO"); summary="Secondary news article covering MLGO's LLVM integration and reported gains."; takeaways=@("Useful for exec-level briefing","Prefer primary Google sources for numbers") },
  @{ slug="mlgo-llvm-docs"; title="LLVM docs: Machine Learning Guided Optimization (MLGO)"; year="2022+"; kind="code"; group="MLGO & RL gyms"; url="https://llvm.org/docs/MLGO.html"; contrib=@("In-tree flags and interactive model runners","Embedding frameworks notes"); summary="Official LLVM documentation for enabling and interacting with MLGO advisors."; takeaways=@("Operational reference for practitioners","Shows how models plug into compilation") },
  @{ slug="compilergym"; title="CompilerGym (Meta/FAIR)"; year="2022"; kind="code"; group="MLGO & RL gyms"; url="https://github.com/facebookresearch/CompilerGym"; contrib=@("Gym environments for LLVM optimization","Batteries-included benchmarks and rewards","Lowered barrier for RL-for-compilers"); summary="Open toolkit exposing compiler optimization problems as RL environments with datasets and leaderboards."; takeaways=@("Direct ancestor of many LLM pass-ordering setups","Great for reproducible baselines") },
  @{ slug="llvm-gsoc-pass-ordering"; title="LLVM Discourse: ML-guided ordering of compiler optimization passes (GSoC)"; year="2022"; kind="forum"; group="MLGO & RL gyms"; url="https://discourse.llvm.org/t/machine-learning-guided-ordering-of-compiler-optimization-passes/60415"; contrib=@("Community project discussion on learned pass pipelines","Links CompilerGym contributors"); summary="Forum thread organizing GSoC-style work on replacing fixed O2/O3 pipelines with learned pass orders."; takeaways=@("Shows community demand pre-LLM boom","Useful historical context") },
  @{ slug="llm-for-compiler-opt-2023"; title="Large Language Models for Compiler Optimization"; year="2023"; kind="paper"; group="Foundation LLMs for compilers"; url="https://arxiv.org/abs/2309.07062"; contrib=@("7B model emits LLVM pass lists","Auxiliary tasks: predict instr counts and optimized IR","~3% IR size improvement over -Oz without thousands of compiles"); summary="Early demonstration that transformers can choose optimization pass sequences for code size, keeping correctness by executing real compiler passes."; takeaways=@("Template for safe LLM-compiler cooperation","Authors emphasize model IR output is untrusted","Spawned HN discussion clarifying phase ordering vs neural rewrite") },
  @{ slug="meta-llm-compiler"; title="Meta Large Language Model Compiler: Foundation Models of Compiler Optimization"; year="2024"; kind="paper"; group="Foundation LLMs for compilers"; url="https://arxiv.org/abs/2407.02524"; contrib=@("Open foundation models on 546B IR/asm tokens","Instruction tuning for compiler emulation","FTD models for size optimization and disassembly"); summary="Code-Llama-based foundation models specialized for compiler IR/assembly reasoning; fine-tunes achieve a large fraction of autotuning size gains without iterative compiles."; takeaways=@("Best starting checkpoint family for IR tasks","Disassembly still limited exact-match","Released to accelerate community research (CC'25)") },
  @{ slug="meta-llm-compiler-page"; title="Meta AI publication page: LLM Compiler"; year="2024"; kind="company"; group="Foundation LLMs for compilers"; url="https://ai.meta.com/research/publications/meta-large-language-model-compiler-foundation-models-of-compiler-optimization/"; contrib=@("Official announcement page"); summary="Meta research landing page for LLM Compiler release."; takeaways=@("Canonical company citation","Pair with arXiv PDF") },
  @{ slug="cummins-linkedin-llm-compiler"; title="Chris Cummins: LLM Compiler foundation models post"; year="2024"; kind="company"; group="Foundation LLMs for compilers"; url="https://www.linkedin.com/pulse/llm-compiler-foundation-models-code-optimization-chris-cummins-ktwyc"; contrib=@("Author-facing narrative of tasks and results"); summary="LinkedIn article by coauthor explaining pretraining tasks and downstream size/disasm fine-tunes."; takeaways=@("Readable companion to the paper","Clarifies intended use cases") },
  @{ slug="compiler-feedback-llms"; title="Compiler generated feedback for Large Language Models"; year="2024"; kind="paper"; group="Foundation LLMs for compilers"; url="https://arxiv.org/abs/2403.14714"; contrib=@("Short/Long/Fast Feedback variants","~10× faster iteration with Fast Feedback","Shows iterative compiler-in-the-loop improvement"); summary="Extends pass-list LLM optimization with structured compiler feedback, analyzing which feedback contents help and the cost of including full IR."; takeaways=@("Feedback design matters as much as the base model","Fast Feedback avoids generating full IR each round") },
  @{ slug="hn-llm-compiler-opt-2023"; title="HN: Large Language Models for Compiler Optimization"; year="2023"; kind="forum"; group="Foundation LLMs for compilers"; url="https://news.ycombinator.com/item?id=37549216"; contrib=@("Author clarifications on pass lists vs codegen","Community discussion of phase ordering"); summary="Hacker News thread where authors explain that correctness comes from executing compiler passes, not trusting model-written IR."; takeaways=@("Excellent pedagogical thread","Common misconception: 'LLM rewrites IR unsafely'") },
  @{ slug="hn-meta-llm-compiler-40819479"; title="HN: Meta LLM Compiler (long thread)"; year="2024"; kind="forum"; group="Foundation LLMs for compilers"; url="https://news.ycombinator.com/item?id=40819479"; contrib=@("Deep discussion of size vs speed objectives","Round-trip verification of disassembly"); summary="Extended HN discussion of Meta LLM Compiler tasks, risks, and verification strategies."; takeaways=@("Captures practitioner skepticism and excitement","Useful quotes on deterministic opt mitigating LLM instability") },
  @{ slug="hn-meta-llm-compiler-40812436"; title="HN: Meta Large Language Model Compiler"; year="2024"; kind="forum"; group="Foundation LLMs for compilers"; url="https://news.ycombinator.com/item?id=40812436"; contrib=@("Risk analysis of IR rewrite vs flag selection"); summary="HN thread emphasizing safer use cases: choosing passes/flags rather than rewriting IR directly."; takeaways=@("Reinforces hybrid design principle") },
  @{ slug="compiler-r1"; title="Compiler-R1: Towards Agentic Compiler Auto-tuning with Reinforcement Learning"; year="2025"; kind="paper"; group="Agentic & RL compilers"; url="https://arxiv.org/html/2506.15701v1"; contrib=@("SFT then RL for tool-using pass agents","Curated reasoning dataset (~19.6k samples)","Average ~8.46% IR instruction-count reduction vs -Oz"); summary="NeurIPS 2025 framework training LLMs to interact with compiler tools and discover pass sequences via outcome-based RL."; takeaways=@("First prominent RL-trained LLM compiler agent story","Tool use is first-class","Compare carefully to size vs runtime objectives") },
  @{ slug="compiler-r1-github"; title="Mind4Compiler/Compiler-R1 (code)"; year="2025"; kind="code"; group="Agentic & RL compilers"; url="https://github.com/Mind4Compiler/Compiler-R1"; contrib=@("Open training pipelines and datasets"); summary="Public code repository accompanying Compiler-R1."; takeaways=@("Reproduce or extend agent training here") },
  @{ slug="llm-veriopt"; title="LLM-VeriOpt: Verification-Guided RL for LLM-Based Compiler Optimization"; year="2026"; kind="paper"; group="Agentic & RL compilers"; url="https://2026.cgo.org/details/cgo-2026-papers/37/LLM-VeriOpt-Verification-Guided-Reinforcement-Learning-for-LLM-Based-Compiler-Optimi"; contrib=@("Alive2 signals in GRPO rewards","Small Qwen-3B trained as peephole optimizer","~90% verifiably correct; emergent opts beating instcombine in 20% cases"); summary="CGO 2026 paper showing formal verification feedback can train small LLMs to perform correct LLVM IR peephole optimizations better than larger untuned models."; takeaways=@("Verification-in-the-loop is a major correctness path","Small specialized models can beat large general ones","Scope is local peephole, not whole-program") },
  @{ slug="magellan"; title="Magellan: Autonomous Discovery of Novel Compiler Optimization Heuristics with AlphaEvolve"; year="2026"; kind="paper"; group="Agentic & RL compilers"; url="https://arxiv.org/abs/2601.21096"; contrib=@("Evolves executable C++ heuristics via LLM+evolution","LLVM inlining/regalloc; XLA experiments","Produces human-readable deployable code unlike neural policies"); summary="Google/DeepMind/Cornell agentic framework that synthesizes compiler pass decision logic and evaluates it on macro-benchmarks, matching or beating expert heuristics."; takeaways=@("Offline compiler-engineering agent archetype","Production inlining narrative in talks","Bridge between AlphaEvolve and compilers") },
  @{ slug="magellan-llvm-slides"; title="LLVM Developers' Meeting slides: Magellan"; year="2025"; kind="talk"; group="Agentic & RL compilers"; url="https://llvm.org/devmtg/2025-10/slides/technical_talks/chen.pdf"; contrib=@("Production inlining context (Chrome/Fuchsia/etc.)","XLA auto-sharding contest results notes"); summary="Talk slides presenting Magellan case studies and next steps including open-source ambitions."; takeaways=@("More operational detail than the paper abstract","Good for industry relevance arguments") },
  @{ slug="alphaevolve-paper"; title="AlphaEvolve: A coding agent for scientific and algorithmic discovery"; year="2025"; kind="paper"; group="Agentic & RL compilers"; url="https://arxiv.org/abs/2506.13131"; contrib=@("Evolutionary coding agent framework","Used across math/CS and infra optimizations"); summary="DeepMind paper describing AlphaEvolve, the evolutionary LLM coding agent later used by Magellan for compiler heuristics."; takeaways=@("General agent substrate, not compiler-specific","Pairs with Magellan and DeepMind impact blog") },
  @{ slug="alphaevolve-blog"; title="DeepMind blog: AlphaEvolve impact"; year="2026"; kind="company"; group="Agentic & RL compilers"; url="https://deepmind.google/blog/alphaevolve-impact/"; contrib=@("Production infra impacts (TPU, Spanner, storage footprint)","Positions AlphaEvolve as general optimization agent"); summary="Company post summarizing a year of AlphaEvolve deployments including compiler-related storage footprint improvements."; takeaways=@("Signals industrial seriousness","Compiler opts are one of several domains") },
  @{ slug="awarecompiler"; title="AwareCompiler: Agentic Context-Aware Compiler Optimization"; year="2025"; kind="paper"; group="Agentic & RL compilers"; url="https://arxiv.org/html/2510.11759v1"; contrib=@("Symbolic knowledge base bridging code features and passes","Adaptive pass generation","Hybrid training with composite rewards"); summary="Agentic framework attacking semantic misalignment, poor agent-compiler interaction, and reward sparsity in pass optimization."; takeaways=@("Emphasizes knowledge + data synergy","Models optimization as multi-turn agent-env interaction") },
  @{ slug="autopass"; title="AutoPass: Evidence-Guided LLM Agents for Compiler Performance Tuning"; year="2026"; kind="paper"; group="Agentic & RL compilers"; url="https://arxiv.org/pdf/2606.20373"; contrib=@("Inference-only multi-agent tuning","Uses compiler logs/profiles as evidence","Avoids costly offline RL retraining"); summary="Practical agent system for runtime-oriented compiler tuning under evaluation budgets, contrasting with heavyweight learned policies."; takeaways=@("Strong 'deploy without retraining' angle","Evidence/profile grounding is the key idea") },
  @{ slug="hintpilot"; title="HintPilot: LLM-based Compiler Hint Synthesis for Code Optimization"; year="2026"; kind="paper"; group="Agentic & RL compilers"; url="https://arxiv.org/abs/2604.15041"; contrib=@("RAG over compiler documentation for hints","Semantics-preserving pragma/attribute insertion","Up to 6.88× geo-mean vs -Ofast on reported benches"); summary="ACL Findings 2026 system that steers compilers via synthesized hints rather than rewriting program semantics."; takeaways=@("Excellent correctness-preserving pattern","Profiling-guided refinement loop","Open code: ZJU-PL/hintpilot") },
  @{ slug="acclaim"; title="Agentic Code Optimization via Compiler-LLM Cooperation (ACCLAIM)"; year="2026"; kind="paper"; group="Agentic & RL compilers"; url="https://arxiv.org/abs/2604.04238"; contrib=@("Multi-agent cooperation across abstraction levels","Compiler tools + LLM rewrites + test agent","Up to 1.25× over compiler-only baselines"); summary="Shows orchestrated agents can interleave deterministic compiler opts with creative LLM rewrites while testing for correctness/performance."; takeaways=@("Budget distribution across levels matters","Tool-calling quality is a bottleneck for open models","Canonical multi-agent compiler design reference") },
  @{ slug="generative-compilation"; title="Generative Compilation: On-the-Fly Compiler Feedback as AI Generates Code"; year="2026"; kind="paper"; group="Agentic & RL compilers"; url="https://arxiv.org/abs/2607.13921"; contrib=@("Sealors turn partial programs into checkable ones","Lean-mechanized properties on a core calculus","Improves Rust compile/functional correctness vs post-hoc feedback"); summary="Makes compilers first-class participants during LLM decoding by diagnosing partial programs early, reducing error cascades."; takeaways=@("Reshapes when compilation happens in AI coding","Especially valuable for strict languages like Rust","Different from pass-ordering papers: frontend generative loop") },
  @{ slug="kernelbench"; title="KernelBench: Can LLMs Write Efficient GPU Kernels?"; year="2025"; kind="paper"; group="GPU kernels & inference compilers"; url="https://arxiv.org/abs/2502.10517"; contrib=@("250 PyTorch→kernel tasks across difficulty levels","fast_p metric (correct and speedup > p)","Shows iterative refinement helps but task remains hard"); summary="ICML 2025 benchmark that standardized evaluation of LLM GPU kernel generation against PyTorch baselines."; takeaways=@("Default benchmark citation for kernel agents","One-shot frontier performance often weak","Feedback loops are necessary") },
  @{ slug="kernelbench-blog"; title="Stanford blog: KernelBench"; year="2025"; kind="company"; group="GPU kernels & inference compilers"; url="https://scalingintelligence.stanford.edu/blogs/kernelbench/"; contrib=@("Public explainer and motivation"); summary="Lab blog introducing KernelBench vision for agentic systems optimization with dense feedback."; takeaways=@("Good outreach companion to the paper") },
  @{ slug="kernelbench-github"; title="ScalingIntelligence/KernelBench"; year="2025"; kind="code"; group="GPU kernels & inference compilers"; url="https://github.com/ScalingIntelligence/KernelBench/"; contrib=@("Open eval harness and tasks"); summary="GitHub repository for KernelBench datasets and evaluation scripts."; takeaways=@("Start here to run comparisons") },
  @{ slug="kernelbench-x"; title="KernelBench-X: A Comprehensive Benchmark for Evaluating LLM-Generated GPU Kernels"; year="2026"; kind="paper"; group="GPU kernels & inference compilers"; url="https://arxiv.org/html/2605.04956v1"; contrib=@("Broader eval across GPUs/methods","Finds refine↑correctness but speedup can fall","Reports many correct kernels slower than eager"); summary="Follow-on benchmark analysis that stresses correctness≠efficiency and highlights fusion difficulty."; takeaways=@("Critical caution against overclaiming agent wins","Use when reviewing GEAK-style iterative loops") },
  @{ slug="geak"; title="GEAK: Introducing Triton Kernel AI Agent & Evaluation Benchmarks"; year="2025"; kind="paper"; group="GPU kernels & inference compilers"; url="https://arxiv.org/html/2507.23194"; contrib=@("Agentic Triton generation for AMD GPUs","Reflexion-style iterative loops","New/revised Triton evaluation suites"); summary="AMD-centered framework for generating efficient Triton kernels with inference-time compute scaling and hardware feedback."; takeaways=@("Industrial vendor commitment to kernel agents","Portability story beyond NVIDIA","Pair with ROCm blog and GitHub agent") },
  @{ slug="geak-rocm-blog"; title="AMD ROCm blog: Triton kernel AI / GEAK"; year="2025"; kind="company"; group="GPU kernels & inference compilers"; url="https://rocm.blogs.amd.com/software-tools-optimization/triton-kernel-ai/README.html"; contrib=@("Vendor announcement and benchmark tables"); summary="ROCm engineering blog announcing GEAK and Triton evaluation benchmarks on Instinct GPUs."; takeaways=@("Numbers and product framing","Good for industry survey sections") },
  @{ slug="geak-github"; title="AMD-AGI/GEAK agent"; year="2025"; kind="code"; group="GPU kernels & inference compilers"; url="https://github.com/AMD-AGI/GEAK-agent"; contrib=@("Kernel workflow + e2e serving workflow"); summary="Open agent repository for single-kernel and whole-model serving optimization loops on AMD."; takeaways=@("Shows evolution from paper agent to broader productized workflows") },
  @{ slug="kernelllm"; title="Meta KernelLLM (Hugging Face)"; year="2025"; kind="company"; group="GPU kernels & inference compilers"; url="https://huggingface.co/facebook/KernelLLM"; contrib=@("8B Llama fine-tuned for PyTorch→Triton","Trained on paired torch/triton data","Competitive Pass@k on KernelBench-Triton"); summary="Specialized small model demonstrating that domain-focused fine-tunes can rival much larger general LLMs on Triton kernel generation."; takeaways=@("Specialization > scale for narrow compiler DSLs","Complements Meta LLM Compiler (IR) with Triton focus") },
  @{ slug="reasoning-compiler"; title="Reasoning Compiler: LLM-Guided Optimizations for Efficient Model Serving"; year="2025"; kind="paper"; group="GPU kernels & inference compilers"; url="https://arxiv.org/html/2506.01374"; contrib=@("LLM proposals inside MCTS over TVM schedules","Context-aware sequential decisions","Sample-efficiency vs evolutionary MetaSchedule"); summary="NeurIPS 2025 compilation framework for serving kernels that uses LLMs as proposal mechanisms within structured search."; takeaways=@("Blueprint for LLM+search hybrids","Evaluates realistic serving kernels (attention, MoE, etc.)") },
  @{ slug="agentcompile"; title="AgentCompile: An LLM-Guided Compiler for Direct CUDA Inference"; year="2026"; kind="paper"; group="GPU kernels & inference compilers"; url="https://arxiv.org/html/2606.07665"; contrib=@("LLM advisory metadata only","Compiler-defined bounded CUDA candidate spaces","End-to-end speedups vs PyTorch eager on small LLMs"); summary="Hybrid inference compiler where the LLM prioritizes candidates but templates, checks, validation, and fallback remain compiler-controlled."; takeaways=@("Textbook hybrid architecture","Separates guidance claims from kernel/runtime effects") },
  @{ slug="mliragent"; title="ucb-bar/mlirAgent"; year="2025"; kind="code"; group="GPU kernels & inference compilers"; url="https://github.com/ucb-bar/mlirAgent"; contrib=@("MCP tool layer for MLIR/LLVM agents","Structural IR fingerprinting","Empirical finding: LLMs weak at direct IR transforms"); summary="Research framework for AI-guided MLIR/LLVM development via tools, knowledge graphs, and evolutionary heuristic optimization."; takeaways=@("Negative result on direct IR rewrite is important","MCP-style tool APIs as agent contracts","Inlining heuristic evolution results") },
  @{ slug="cuda-tile-blog"; title="NVIDIA: Focus on Your Algorithm—CUDA Tile Handles the Hardware"; year="2025"; kind="company"; group="Company infra"; url="https://developer.nvidia.com/blog/focus-on-your-algorithm-nvidia-cuda-tile-handles-the-hardware/"; contrib=@("Introduces CUDA Tile / Tile IR","Tile-level virtual ISA analogous to PTX for SIMT"); summary="NVIDIA technical blog explaining CUDA Tile programming model and Tile IR for portable high-level GPU kernels."; takeaways=@("New IR surface agents may target next","Competes/coexists with Triton abstractions") },
  @{ slug="cuda-tile-cpp"; title="NVIDIA: Develop High-Performance GPU Kernels in C++ with CUDA Tile"; year="2026"; kind="company"; group="Company infra"; url="https://developer.nvidia.com/blog/develop-high-performance-gpu-kernels-in-cpp-with-nvidia-cuda-tile/"; contrib=@("CUDA Tile in C++ codebases"); summary="Follow-on NVIDIA post for expressing tile kernels in C++ atop Tile IR."; takeaways=@("Expands Tile beyond Python cuTile") },
  @{ slug="cuda-13-3-compileiq"; title="NVIDIA CUDA 13.3: Tile C++ + CompileIQ"; year="2026"; kind="company"; group="Company infra"; url="https://developer.nvidia.com/blog/nvidia-cuda-13-3-enhances-gpu-development-with-tile-programming-in-c-compiler-autotuning-and-python-updates/"; contrib=@("Announces CompileIQ autotuner","Claims up to ~15% on hot GEMM/attention kernels"); summary="Release blog bundling CUDA Tile C++ support with CompileIQ evolutionary compiler auto-tuning."; takeaways=@("Compiler knobs themselves become search spaces","Industrial parallel to Magellan-style search, but on NVCC internals") },
  @{ slug="compileiq-deep-dive"; title="NVIDIA: Extract More Kernel Performance with CompileIQ"; year="2026"; kind="company"; group="Company infra"; url="https://developer.nvidia.com/blog/extract-more-kernel-performance-with-nvidia-compileiq-auto-tuning/"; contrib=@("Deep dive on ACF / genetic search","Multi-objective compile-time vs runtime"); summary="Detailed NVIDIA blog on CompileIQ's search over internal compiler parameters via Advanced Controls Files."; takeaways=@("Important vendor datapoint for 'AI compilers' in production toolchains") },
  @{ slug="compileiq-docs"; title="CompileIQ documentation"; year="2026"; kind="code"; group="Company infra"; url="https://nvidia.github.io/CompileIQ/stable/compilers_overview.html"; contrib=@("API for NVCC/PTXAS search spaces"); summary="Official docs for tuning NVIDIA compilers with CompileIQ."; takeaways=@("Practitioner how-to") },
  @{ slug="modular-mlir-blog"; title="Modular: What about the MLIR compiler infrastructure?"; year="2025"; kind="company"; group="Company infra"; url="https://www.modular.com/blog/democratizing-ai-compute-part-8-what-about-the-mlir-compiler-infrastructure"; contrib=@("Historical account of MLIR's rise","Critique of fragmentation and peak-performance gaps"); summary="Chris Lattner series post on MLIR's origins and the difficulty of delivering a beloved end-to-end AI stack."; takeaways=@("Balances academic MLIR optimism with product reality","Useful survey context") },
  @{ slug="anthropic-claude-c-compiler"; title="Anthropic: Building a C compiler with a team of parallel Claudes"; year="2026"; kind="company"; group="Company infra"; url="https://www.anthropic.com/engineering/building-c-compiler"; contrib=@("16 agents build ~100kLoC Rust C compiler","Linux 6.9 multi-arch builds","Harness/tests as the real product"); summary="Engineering experiment showing agent teams can implement a serious compiler given strong oracles and harnesses."; takeaways=@("Agents as compiler engineers (adjacent to compile-time agents)","Security/verification concerns acknowledged by author") },
  @{ slug="ars-claude-c-compiler"; title="Ars Technica: Sixteen Claude agents created a C compiler"; year="2026"; kind="company"; group="Company infra"; url="https://arstechnica.com/ai/2026/02/sixteen-claude-ai-agents-working-together-created-a-new-c-compiler/"; contrib=@("Press summary of Anthropic experiment"); summary="News coverage of the Claude C compiler agent-team project."; takeaways=@("Public impact narrative") },
  @{ slug="modular-claude-c-compiler"; title="Modular/Lattner: The Claude C Compiler — Future of Software"; year="2026"; kind="company"; group="Company infra"; url="https://www.modular.com/blog/the-claude-c-compiler-what-it-reveals-about-the-future-of-software"; contrib=@("Expert interpretation of CCC milestone","Organizational adaptation advice"); summary="Lattner reflection treating CCC as real progress while emphasizing tests/harnesses and engineering practice changes."; takeaways=@("High-signal industry commentary","Links compiler construction to AI tooling strategy") },
  @{ slug="hn-claude-c-compiler"; title="HN: We tasked Opus 4.6 agent teams to build a C Compiler"; year="2026"; kind="forum"; group="Company infra"; url="https://news.ycombinator.com/item?id=46903616"; contrib=@("Technical caveats (16-bit boot, GCC oracle, assembler)"); summary="Large HN thread dissecting what CCC did and did not achieve."; takeaways=@("Essential skepticism companion to the Anthropic post") },
  @{ slug="llvm-ml-workshop-2025"; title="LLVM Discourse: LLVM ♥ ML Workshop 2025 agenda"; year="2025"; kind="forum"; group="Forums & workshops"; url="https://discourse.llvm.org/t/llvm-dev25-llvm-ml-workshop/87488/4"; contrib=@("Agenda including Magellan, MLGO lessons, IR2Vec"); summary="Community workshop agenda showing active ML/LLM topics inside LLVM Dev Meeting."; takeaways=@("Barometer of LLVM-community AI work") },
  @{ slug="llvm-ml-workshop-2026"; title="LLVM Discourse: LLVM ♥ ML Workshop 2026 CFP"; year="2026"; kind="forum"; group="Forums & workshops"; url="https://discourse.llvm.org/t/llvm-dev26-llvm-ml-workshop/91148"; contrib=@("Explicit call for agent-based workflows with LLVM"); summary="Workshop announcement emphasizing agents, IR comprehension, and dataset curation."; takeaways=@("Signals 2026 community priorities") },
  @{ slug="llvm-ml-workshop-2023"; title="LLVM Discourse: ML-Guided Compiler Optimization Workshop 2023"; year="2023"; kind="forum"; group="Forums & workshops"; url="https://discourse.llvm.org/t/llvm-dev23-ml-guided-compiler-optimization-in-llvm-workshop/73090"; contrib=@("Early LLM discussion notes in LLVM community"); summary="Earlier workshop thread capturing first-wave ideas for LLMs in compiler optimization."; takeaways=@("Historical baseline before foundation LLM Compiler release") },
  @{ slug="llvm-agent-pr-review"; title="LLVM Discourse: Automated review with agents (~30 bugs / 207 PRs)"; year="2026"; kind="forum"; group="Forums & workshops"; url="https://discourse.llvm.org/t/automated-review-with-agents-30-bugs-on-207-prs/90093"; contrib=@("Compiler-specific agent tools beat generic SWE agents","Reports many real optimization bugs"); summary="Experience report on agentic review of LLVM optimization PRs using specialized toolkits and pass knowledge."; takeaways=@("Domain tools > generic agents","Another agent role: compiler reviewer") },
  @{ slug="compilers-magellan-notice"; title="comp.compilers: Magellan paper notice"; year="2026"; kind="forum"; group="Forums & workshops"; url="https://compilers.iecc.com/comparch/article/26-01-006"; contrib=@("Classic mailing-list pointer to Magellan"); summary="Short notice circulating the Magellan preprint to the traditional compilers community."; takeaways=@("Shows crossover into classic compiler forums") },
  @{ slug="ieee-pulse-llm-compilers"; title="IEEE Pulse: LLMs in Compiler Optimization — Challenges and Future Direction"; year="2025"; kind="company"; group="Forums & workshops"; url="https://www.embs.org/pulse/articles/llms-in-compiler-optimization-challenges-and-future-direction/"; contrib=@("Highlights HPC data scarcity challenges"); summary="Perspective article reviewing LLM-for-compiler work and stressing dataset/cost limits in HPC settings."; takeaways=@("Good for gaps section citations") },
  @{ slug="moonlight-magellan-review"; title="Moonlight literature review: Magellan"; year="2026"; kind="company"; group="Forums & workshops"; url="https://www.themoonlight.io/en/review/magellan-autonomous-discovery-of-novel-compiler-optimization-heuristics-with-alphaevolve"; contrib=@("Secondary structured review of Magellan"); summary="Third-party literature review summarizing Magellan methodology and case studies."; takeaways=@("Handy digest; verify claims against primary paper") },
  @{ slug="souper"; title="Souper: A superoptimizer for LLVM IR"; year="2010s+"; kind="code"; group="Correctness lineage"; url="https://github.com/google/souper"; contrib=@("SMT-based peephole discovery","Historical neighbor to Alive/Alive2 lines"); summary="Classic LLVM IR superoptimizer using solvers to find missing peephole optimizations."; takeaways=@("Pre-LLM correctness/optimization discovery lineage","Useful contrast to LLM-VeriOpt") }
)

function Write-Digest($it) {
  $path = Join-Path $pubDir ($it.slug + ".md")
  $contrib = ($it.contrib | ForEach-Object { "- $_" }) -join "`n"
  $takes = ($it.takeaways | ForEach-Object { "- $_" }) -join "`n"
  $body = @"
# $($it.title)

| Field | Value |
|---|---|
| **Year** | $($it.year) |
| **Type** | $($it.kind) |
| **Group** | $($it.group) |
| **Link** | [$($it.url)]($($it.url)) |

## Key contributions

$contrib

## Summary

$($it.summary)

## Key takeaways

$takes

## Why it matters for this survey

This source informs the living survey in ``docs/SURVEY.md`` (trends, agent roles, process reshape, and/or gaps). Prefer the primary link above when citing.
"@
  Set-Content -Path $path -Value $body -Encoding UTF8
}

foreach ($it in $items) { Write-Digest $it }

# INDEX
$indexRows = $items | ForEach-Object {
  "| $($_.year) | $($_.kind) | $($_.group) | [$($_.title)]($($_.slug).md) | [source]($($_.url)) |"
}
$index = @"
# Publications index

One digest per searched source. Files live beside this index.

| Year | Kind | Group | Digest | Source |
|---|---|---|---|---|
$($indexRows -join "`n")

**Total:** $($items.Count) digests

Kinds: ``paper`` · ``company`` · ``forum`` · ``talk`` · ``code``
"@
Set-Content -Path (Join-Path $pubDir "INDEX.md") -Value $index -Encoding UTF8
Write-Output "Wrote $($items.Count) digests + INDEX.md to $pubDir"
